local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ver = require(ReplicatedStorage.Shared.Classes.ver)
local ko = Instance.new("IntValue")
ko.Parent = ReplicatedStorage
ko.Name = "KOs"
-- local workspace = game:GetService("Workspace")
-- local model = workspace
-- local Gui = game:GetService("StarterGui")
-- local Workspace = game:GetService("Workspace")
print("Citiontino (Client) " .. ver.version)
-- Changed Idea
